import type {
  Pratica,
  BollaDoganale,
  TerminalContainer,
  Trasporto,
  Fattura,
  AgentRun,
  KpiData,
} from "./types";

// ─── CLIENTI REALI (anonimizzati ma plausibili) ──────────────────────────────
const CLIENTI = [
  { id: "c001", nome: "Tessuti Mediterraneo S.r.l.", piva: "IT06234580638", citta: "Napoli" },
  { id: "c002", nome: "Galileo Import Export S.p.A.", piva: "IT07845921074", citta: "Milano" },
  { id: "c003", nome: "Casa Bella Living S.r.l.", piva: "IT05123456789", citta: "Roma" },
  { id: "c004", nome: "Magnolia Distribuzione S.r.l.", piva: "IT09812345671", citta: "Napoli" },
  { id: "c005", nome: "Vesuvio Logistica S.p.A.", piva: "IT04567891230", citta: "Pompei" },
  { id: "c006", nome: "Aurora Fashion Group S.r.l.", piva: "IT08234567899", citta: "Prato" },
  { id: "c007", nome: "Partenope Forniture S.r.l.", piva: "IT07654321098", citta: "Caserta" },
  { id: "c008", nome: "Sirena Trade Co. S.r.l.", piva: "IT06789012345", citta: "Salerno" },
  { id: "c009", nome: "Etna Casalinghi S.p.A.", piva: "IT05432109876", citta: "Catania" },
  { id: "c010", nome: "Lago Maggiore Import S.r.l.", piva: "IT04321098765", citta: "Verbania" },
];

const NAVI = [
  { nome: "BANGKOK EXPRESS", compagnia: "Hapag-Lloyd", mmsi: "211879870" },
  { nome: "MSC GAYANE", compagnia: "MSC", mmsi: "636019825" },
  { nome: "MAERSK HONAM", compagnia: "Maersk", mmsi: "563089800" },
  { nome: "CMA CGM JACQUES SAADE", compagnia: "CMA CGM", mmsi: "228396800" },
  { nome: "ONE STORK", compagnia: "ONE", mmsi: "354710000" },
  { nome: "EVER GIVEN", compagnia: "Evergreen", mmsi: "353136000" },
  { nome: "COSCO SHIPPING UNIVERSE", compagnia: "COSCO", mmsi: "477001800" },
  { nome: "HMM ALGECIRAS", compagnia: "HMM", mmsi: "440104000" },
];

const PORTI_CINA = ["SHANGHAI", "NINGBO", "YANTIAN", "QINGDAO", "XIAMEN", "GUANGZHOU"];
const TERMINAL_NAPOLI = ["CT Napoli", "Soteco", "Conateco", "FlavioGioia"];
const SHIPPERS_CINA = [
  "Shanghai Textile Import Co. Ltd",
  "Ningbo Goldway Industries",
  "Yantian Sunrise Trading",
  "Qingdao Pacific Manufacturing",
  "Guangzhou Pearl River Exports",
  "Xiamen Coastal Industries",
];
const MERCI = [
  "Tessuti per arredamento - 480 rotoli",
  "Casalinghi assortiti - 1200 cartoni",
  "Calzature sportive - 8500 paia",
  "Componenti elettronici - 320 cartoni",
  "Mobili da giardino - 156 colli",
  "Articoli da regalo - 2400 cartoni",
  "Abbigliamento donna - 3200 capi",
  "Giocattoli plastica - 1800 cartoni",
];

// ─── Helpers per date ─────────────────────────────────────────────────────────
const today = new Date("2026-05-25");
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const daysFromNow = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

// ─── PRATICHE ─────────────────────────────────────────────────────────────────
export const PRATICHE_MOCK: Pratica[] = [
  {
    id: "p001",
    numero: "PF-2026-0148",
    cliente: CLIENTI[0].nome,
    clienteId: CLIENTI[0].id,
    shipper: SHIPPERS_CINA[0],
    paeseOrigine: "CN",
    portoCarico: "SHANGHAI",
    portoScarico: "NAPOLI",
    nave: NAVI[0].nome,
    viaggio: "012E",
    mmsi: NAVI[0].mmsi,
    blNumber: "HLCUSHA240591234",
    bookingNumber: "BK7891244",
    containerCount: 2,
    containerType: "40HC",
    pesoKg: 18450,
    valoreEur: 84500,
    descrizioneMerce: MERCI[0],
    etdCina: daysAgo(28),
    etaItalia: daysFromNow(3),
    stato: "in_arrivo",
    urgenza: "alta",
    stepCorrente: 4,
    operatore: "Luca De Marco",
    team: "import",
    compagnia: NAVI[0].compagnia,
    createdAt: daysAgo(31),
    updatedAt: daysAgo(1),
    documenti: [
      {
        id: "d101",
        praticaId: "p001",
        nome: "Booking_Confirmation_HL_BK7891244.pdf",
        tipo: "altro",
        size: 184320,
        uploadedAt: daysAgo(30),
        uploadedBy: "Luca De Marco",
      },
      {
        id: "d102",
        praticaId: "p001",
        nome: "BL_HLCUSHA240591234.pdf",
        tipo: "bl",
        size: 412800,
        uploadedAt: daysAgo(20),
        uploadedBy: "AI:DocCheckAgent",
      },
      {
        id: "d103",
        praticaId: "p001",
        nome: "Commercial_Invoice_TM-2024-0148.pdf",
        tipo: "fattura_commerciale",
        size: 256000,
        uploadedAt: daysAgo(8),
        uploadedBy: "Tessuti Mediterraneo S.r.l.",
      },
      {
        id: "d104",
        praticaId: "p001",
        nome: "Packing_List_TM-2024-0148.xlsx",
        tipo: "packing_list",
        size: 94720,
        uploadedAt: daysAgo(8),
        uploadedBy: "Tessuti Mediterraneo S.r.l.",
      },
    ],
    eventi: [
      {
        id: "e1011",
        praticaId: "p001",
        tipo: "creazione",
        testo: "Pratica creata dall'email cliente",
        attore: "AI:EmailReaderAgent",
        timestamp: daysAgo(31),
      },
      {
        id: "e1012",
        praticaId: "p001",
        tipo: "ai_eseguito",
        testo: "Booking richiesto a Hapag-Lloyd",
        attore: "AI:BookingAgent",
        timestamp: daysAgo(30),
      },
      {
        id: "e1013",
        praticaId: "p001",
        tipo: "step_completato",
        testo: "Booking confermato — BK7891244",
        attore: "Luca De Marco",
        timestamp: daysAgo(30),
      },
      {
        id: "e1014",
        praticaId: "p001",
        tipo: "ai_eseguito",
        testo: "Monitoraggio AIS attivo, ETA: " + daysFromNow(3).slice(0, 10),
        attore: "AI:VesselTrackerAgent",
        timestamp: daysAgo(15),
      },
      {
        id: "e1015",
        praticaId: "p001",
        tipo: "documento_caricato",
        testo: "Documentazione ricevuta dal cliente",
        attore: "Tessuti Mediterraneo S.r.l.",
        timestamp: daysAgo(8),
      },
      {
        id: "e1016",
        praticaId: "p001",
        tipo: "ai_eseguito",
        testo: "Documenti verificati: completi e conformi",
        attore: "AI:DocCheckAgent",
        timestamp: daysAgo(7),
      },
      {
        id: "e1017",
        praticaId: "p001",
        tipo: "alert",
        testo: "Nave in arrivo tra 3 giorni — preparare bolla doganale",
        attore: "AI:Master Orchestrator",
        timestamp: daysAgo(1),
      },
    ],
  },
  {
    id: "p002",
    numero: "PF-2026-0147",
    cliente: CLIENTI[1].nome,
    clienteId: CLIENTI[1].id,
    shipper: SHIPPERS_CINA[1],
    paeseOrigine: "CN",
    portoCarico: "NINGBO",
    portoScarico: "NAPOLI",
    nave: NAVI[1].nome,
    viaggio: "MX408A",
    mmsi: NAVI[1].mmsi,
    blNumber: "MSCUNB2405123",
    bookingNumber: "MSC-NB-9912",
    containerCount: 1,
    containerType: "40HC",
    pesoKg: 9230,
    valoreEur: 62300,
    descrizioneMerce: MERCI[1],
    etdCina: daysAgo(35),
    etaItalia: daysAgo(2),
    stato: "in_terminal",
    urgenza: "critica",
    stepCorrente: 7,
    operatore: "Luca De Marco",
    team: "import",
    compagnia: NAVI[1].compagnia,
    terminal: TERMINAL_NAPOLI[1],
    createdAt: daysAgo(38),
    updatedAt: daysAgo(1),
    documenti: [],
    eventi: [],
  },
  {
    id: "p003",
    numero: "PF-2026-0146",
    cliente: CLIENTI[2].nome,
    clienteId: CLIENTI[2].id,
    shipper: SHIPPERS_CINA[2],
    paeseOrigine: "CN",
    portoCarico: "YANTIAN",
    portoScarico: "NAPOLI",
    nave: NAVI[2].nome,
    viaggio: "240E",
    mmsi: NAVI[2].mmsi,
    blNumber: "MAEU240498765",
    bookingNumber: "MK-YT-7754",
    containerCount: 3,
    containerType: "40HC",
    pesoKg: 24580,
    valoreEur: 142000,
    descrizioneMerce: MERCI[2],
    etdCina: daysAgo(42),
    etaItalia: daysAgo(8),
    stato: "in_dogana",
    urgenza: "alta",
    stepCorrente: 6,
    operatore: "Anna Romano",
    team: "dogana",
    compagnia: NAVI[2].compagnia,
    terminal: TERMINAL_NAPOLI[0],
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
    documenti: [],
    eventi: [],
  },
  {
    id: "p004",
    numero: "PF-2026-0145",
    cliente: CLIENTI[3].nome,
    clienteId: CLIENTI[3].id,
    shipper: SHIPPERS_CINA[3],
    paeseOrigine: "CN",
    portoCarico: "QINGDAO",
    portoScarico: "NAPOLI",
    nave: NAVI[3].nome,
    viaggio: "FAL5-024",
    mmsi: NAVI[3].mmsi,
    blNumber: "CMAUQD240329011",
    bookingNumber: "CMA-QD-5521",
    containerCount: 1,
    containerType: "40HC",
    pesoKg: 8120,
    valoreEur: 54200,
    descrizioneMerce: MERCI[3],
    etdCina: daysAgo(50),
    etaItalia: daysAgo(15),
    stato: "in_consegna",
    urgenza: "normale",
    stepCorrente: 9,
    operatore: "Luca De Marco",
    team: "trasporti",
    compagnia: NAVI[3].compagnia,
    createdAt: daysAgo(53),
    updatedAt: daysAgo(0),
    documenti: [],
    eventi: [],
  },
  {
    id: "p005",
    numero: "PF-2026-0144",
    cliente: CLIENTI[4].nome,
    clienteId: CLIENTI[4].id,
    shipper: SHIPPERS_CINA[4],
    paeseOrigine: "CN",
    portoCarico: "GUANGZHOU",
    portoScarico: "NAPOLI",
    nave: NAVI[4].nome,
    viaggio: "MS027",
    mmsi: NAVI[4].mmsi,
    blNumber: "ONEYGZ240117654",
    bookingNumber: "ONE-GZ-3398",
    containerCount: 2,
    containerType: "40HC",
    pesoKg: 17850,
    valoreEur: 96400,
    descrizioneMerce: MERCI[4],
    etdCina: daysAgo(58),
    etaItalia: daysAgo(22),
    stato: "consegnata",
    urgenza: "normale",
    stepCorrente: 10,
    operatore: "Anna Romano",
    team: "trasporti",
    compagnia: NAVI[4].compagnia,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
    documenti: [],
    eventi: [],
  },
  {
    id: "p006",
    numero: "PF-2026-0143",
    cliente: CLIENTI[5].nome,
    clienteId: CLIENTI[5].id,
    shipper: SHIPPERS_CINA[5],
    paeseOrigine: "CN",
    portoCarico: "XIAMEN",
    portoScarico: "NAPOLI",
    nave: NAVI[5].nome,
    viaggio: "201E",
    mmsi: NAVI[5].mmsi,
    blNumber: "EGLVXM240054321",
    bookingNumber: "EG-XM-1198",
    containerCount: 4,
    containerType: "40HC",
    pesoKg: 32400,
    valoreEur: 184500,
    descrizioneMerce: MERCI[5],
    etdCina: daysAgo(65),
    etaItalia: daysAgo(28),
    stato: "fatturata",
    urgenza: "bassa",
    stepCorrente: 12,
    operatore: "Anna Romano",
    team: "contabilita",
    compagnia: NAVI[5].compagnia,
    createdAt: daysAgo(68),
    updatedAt: daysAgo(5),
    documenti: [],
    eventi: [],
  },
  {
    id: "p007",
    numero: "PF-2026-0149",
    cliente: CLIENTI[6].nome,
    clienteId: CLIENTI[6].id,
    shipper: SHIPPERS_CINA[0],
    paeseOrigine: "CN",
    portoCarico: "SHANGHAI",
    portoScarico: "NAPOLI",
    nave: NAVI[6].nome,
    viaggio: "AEX2-031",
    mmsi: NAVI[6].mmsi,
    blNumber: "COSU240601122",
    bookingNumber: "COSCO-SH-7733",
    containerCount: 1,
    containerType: "40HC",
    pesoKg: 11200,
    valoreEur: 47800,
    descrizioneMerce: MERCI[6],
    etdCina: daysAgo(18),
    etaItalia: daysFromNow(15),
    stato: "in_navigazione",
    urgenza: "normale",
    stepCorrente: 3,
    operatore: "Luca De Marco",
    team: "import",
    compagnia: NAVI[6].compagnia,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(0),
    documenti: [],
    eventi: [],
  },
  {
    id: "p008",
    numero: "PF-2026-0150",
    cliente: CLIENTI[7].nome,
    clienteId: CLIENTI[7].id,
    shipper: SHIPPERS_CINA[1],
    paeseOrigine: "CN",
    portoCarico: "NINGBO",
    portoScarico: "NAPOLI",
    nave: NAVI[7].nome,
    viaggio: "FE5-012",
    mmsi: NAVI[7].mmsi,
    blNumber: "HDMUNB240091234",
    bookingNumber: "HMM-NB-4421",
    containerCount: 2,
    containerType: "40HC",
    pesoKg: 19340,
    valoreEur: 78900,
    descrizioneMerce: MERCI[7],
    etdCina: daysAgo(10),
    etaItalia: daysFromNow(22),
    stato: "booking_aperto",
    urgenza: "normale",
    stepCorrente: 2,
    operatore: "Luca De Marco",
    team: "import",
    compagnia: NAVI[7].compagnia,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(0),
    documenti: [],
    eventi: [],
  },
];

// ─── BOLLE DOGANALI ───────────────────────────────────────────────────────────
export const BOLLE_MOCK: BollaDoganale[] = [
  {
    id: "b001",
    numero: "BD-2026-00148",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    cliente: CLIENTI[2].nome,
    stato: "in_approvazione",
    valoreEur: 142000,
    daziEur: 8520,
    ivaEur: 33114,
    totale: 183634,
    containerCount: 3,
    compilataIl: daysAgo(2),
    precompilataDa: "AI:CustomsFilerAgent",
  },
  {
    id: "b002",
    numero: "BD-2026-00147",
    praticaId: "p004",
    praticaNumero: "PF-2026-0145",
    cliente: CLIENTI[3].nome,
    stato: "accettata",
    valoreEur: 54200,
    daziEur: 2710,
    ivaEur: 12521,
    totale: 69431,
    containerCount: 1,
    compilataIl: daysAgo(14),
    inviataIl: daysAgo(13),
    precompilataDa: "AI:CustomsFilerAgent",
  },
  {
    id: "b003",
    numero: "BD-2026-00146",
    praticaId: "p005",
    praticaNumero: "PF-2026-0144",
    cliente: CLIENTI[4].nome,
    stato: "accettata",
    valoreEur: 96400,
    daziEur: 5784,
    ivaEur: 22481,
    totale: 124665,
    containerCount: 2,
    compilataIl: daysAgo(21),
    inviataIl: daysAgo(20),
    precompilataDa: "AI:CustomsFilerAgent",
  },
  {
    id: "b004",
    numero: "BD-2026-00149",
    praticaId: "p002",
    praticaNumero: "PF-2026-0147",
    cliente: CLIENTI[1].nome,
    stato: "bozza",
    valoreEur: 62300,
    daziEur: 3115,
    ivaEur: 14391,
    totale: 79806,
    containerCount: 1,
    compilataIl: daysAgo(0),
    precompilataDa: "AI:CustomsFilerAgent",
  },
];

// ─── TERMINAL CONTAINER ───────────────────────────────────────────────────────
export const TERMINAL_MOCK: TerminalContainer[] = [
  {
    id: "tc001",
    praticaId: "p002",
    praticaNumero: "PF-2026-0147",
    containerNumber: "MSCU7234119",
    tipo: "40HC",
    terminal: TERMINAL_NAPOLI[1],
    carrier: "MSC",
    arrivoTerminal: daysAgo(2),
    costoGiornaliero: 85,
    costoCumulato: 170,
    stato: "in_sosta",
    cliente: CLIENTI[1].nome,
    alert: "ok",
  },
  {
    id: "tc002",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    containerNumber: "MAEU8912234",
    tipo: "40HC",
    terminal: TERMINAL_NAPOLI[0],
    carrier: "Maersk",
    arrivoTerminal: daysAgo(8),
    costoGiornaliero: 110,
    costoCumulato: 880,
    stato: "in_sosta",
    cliente: CLIENTI[2].nome,
    alert: "costo_alto",
  },
  {
    id: "tc003",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    containerNumber: "MAEU8912287",
    tipo: "40HC",
    terminal: TERMINAL_NAPOLI[0],
    carrier: "Maersk",
    arrivoTerminal: daysAgo(8),
    costoGiornaliero: 110,
    costoCumulato: 880,
    stato: "in_sosta",
    cliente: CLIENTI[2].nome,
    alert: "costo_alto",
  },
  {
    id: "tc004",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    containerNumber: "MAEU8912301",
    tipo: "40HC",
    terminal: TERMINAL_NAPOLI[0],
    carrier: "Maersk",
    arrivoTerminal: daysAgo(8),
    costoGiornaliero: 110,
    costoCumulato: 880,
    stato: "in_trasferimento",
    cliente: CLIENTI[2].nome,
    alert: "scadenza_vicina",
  },
  {
    id: "tc005",
    praticaId: "p004",
    praticaNumero: "PF-2026-0145",
    containerNumber: "CMAU3398212",
    tipo: "40HC",
    terminal: TERMINAL_NAPOLI[2],
    carrier: "CMA CGM",
    arrivoTerminal: daysAgo(14),
    uscitaTerminal: daysAgo(1),
    costoGiornaliero: 95,
    costoCumulato: 1235,
    stato: "uscito",
    cliente: CLIENTI[3].nome,
    alert: "ok",
  },
];

// ─── TRASPORTI ────────────────────────────────────────────────────────────────
export const TRASPORTI_MOCK: Trasporto[] = [
  {
    id: "t001",
    praticaId: "p004",
    praticaNumero: "PF-2026-0145",
    vettore: "Autotrasporti Russo S.r.l.",
    vettoreId: "v01",
    containerNumber: "CMAU3398212",
    pickup: "Terminal Conateco — Napoli",
    destinazione: "Magnolia Distribuzione — Casoria (NA)",
    dataPickup: daysFromNow(0),
    oraSlot: "08:00-10:00",
    stato: "confermato",
    cliente: CLIENTI[3].nome,
    contattoCliente: "Sig. Mauro Coppola — 081 5573891",
    notifyClientAt: daysAgo(2),
    confermaClienteAt: daysAgo(1),
  },
  {
    id: "t002",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    vettore: "Trasporti Vesuvio S.p.A.",
    vettoreId: "v02",
    containerNumber: "MAEU8912234",
    pickup: "CT Napoli",
    destinazione: "Casa Bella Living — Pomezia (RM)",
    dataPickup: daysFromNow(2),
    oraSlot: "14:00-16:00",
    stato: "notificato_cliente",
    cliente: CLIENTI[2].nome,
    contattoCliente: "Dott.ssa Federica Lo Russo — 06 9134552",
    notifyClientAt: daysAgo(0),
  },
  {
    id: "t003",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    vettore: "Trasporti Vesuvio S.p.A.",
    vettoreId: "v02",
    containerNumber: "MAEU8912287",
    pickup: "CT Napoli",
    destinazione: "Casa Bella Living — Pomezia (RM)",
    dataPickup: daysFromNow(2),
    oraSlot: "14:00-16:00",
    stato: "schedulato",
    cliente: CLIENTI[2].nome,
    contattoCliente: "Dott.ssa Federica Lo Russo — 06 9134552",
  },
  {
    id: "t004",
    praticaId: "p005",
    praticaNumero: "PF-2026-0144",
    vettore: "Logistica Sud Express S.r.l.",
    vettoreId: "v03",
    containerNumber: "ONEU3398445",
    pickup: "Terminal FlavioGioia — Napoli",
    destinazione: "Vesuvio Logistica — Pompei (NA)",
    dataPickup: daysAgo(20),
    oraSlot: "09:00-11:00",
    stato: "consegnato",
    cliente: CLIENTI[4].nome,
    contattoCliente: "Sig. Antonio Sorrentino — 081 8612234",
  },
];

// ─── FATTURE ──────────────────────────────────────────────────────────────────
export const FATTURE_MOCK: Fattura[] = [
  {
    id: "f001",
    numero: "FA-2026-00284",
    praticaId: "p006",
    praticaNumero: "PF-2026-0143",
    cliente: CLIENTI[5].nome,
    data: daysAgo(3),
    scadenza: daysFromNow(27),
    imponibile: 8420,
    iva: 1852.4,
    totale: 10272.4,
    stato: "emessa",
    voci: [
      { descrizione: "Nolo marittimo Xiamen-Napoli x 4 cnt 40HC", quantita: 4, prezzoUnitario: 1450, totale: 5800 },
      { descrizione: "Spese portuali", quantita: 4, prezzoUnitario: 185, totale: 740 },
      { descrizione: "Sdoganamento e diritti doganali", quantita: 1, prezzoUnitario: 980, totale: 980 },
      { descrizione: "Handling terminal", quantita: 4, prezzoUnitario: 75, totale: 300 },
      { descrizione: "Pratica completa import", quantita: 1, prezzoUnitario: 600, totale: 600 },
    ],
  },
  {
    id: "f002",
    numero: "FA-2026-00283",
    praticaId: "p005",
    praticaNumero: "PF-2026-0144",
    cliente: CLIENTI[4].nome,
    data: daysAgo(18),
    scadenza: daysFromNow(12),
    imponibile: 5240,
    iva: 1152.8,
    totale: 6392.8,
    stato: "inviata",
    voci: [
      { descrizione: "Nolo marittimo Guangzhou-Napoli x 2 cnt 40HC", quantita: 2, prezzoUnitario: 1620, totale: 3240 },
      { descrizione: "Spese portuali e handling", quantita: 1, prezzoUnitario: 520, totale: 520 },
      { descrizione: "Sdoganamento", quantita: 1, prezzoUnitario: 980, totale: 980 },
      { descrizione: "Trasporto consegna", quantita: 1, prezzoUnitario: 500, totale: 500 },
    ],
  },
  {
    id: "f003",
    numero: "FA-2026-00282",
    praticaId: "p004",
    praticaNumero: "PF-2026-0145",
    cliente: CLIENTI[3].nome,
    data: daysAgo(2),
    scadenza: daysFromNow(28),
    imponibile: 3950,
    iva: 869,
    totale: 4819,
    stato: "bozza",
    voci: [
      { descrizione: "Nolo marittimo Qingdao-Napoli x 1 cnt 40HC", quantita: 1, prezzoUnitario: 1780, totale: 1780 },
      { descrizione: "Spese portuali e handling", quantita: 1, prezzoUnitario: 290, totale: 290 },
      { descrizione: "Sdoganamento", quantita: 1, prezzoUnitario: 980, totale: 980 },
      { descrizione: "Trasporto consegna Pomezia", quantita: 1, prezzoUnitario: 900, totale: 900 },
    ],
  },
];

// ─── AGENT RUNS ───────────────────────────────────────────────────────────────
export const AGENT_RUNS_MOCK: AgentRun[] = [
  {
    id: "ar001",
    agentName: "VesselTrackerAgent",
    agentLabel: "Vessel Tracker",
    praticaId: "p001",
    praticaNumero: "PF-2026-0148",
    stato: "completed",
    startedAt: new Date(today.getTime() - 12 * 60 * 1000).toISOString(),
    completedAt: new Date(today.getTime() - 11 * 60 * 1000).toISOString(),
    durationMs: 4200,
    tokensIn: 320,
    tokensOut: 180,
    costoEur: 0.012,
    output: "Bangkok Express, MMSI 211879870 — posizione: 36.5N 14.8E (Mediterraneo). Velocità 18.4kn. ETA Napoli confermata: 28/05/2026. Nessun ritardo.",
    validationByMaster: "ok",
  },
  {
    id: "ar002",
    agentName: "DocCheckAgent",
    agentLabel: "Document Checker",
    praticaId: "p001",
    praticaNumero: "PF-2026-0148",
    stato: "completed",
    startedAt: new Date(today.getTime() - 35 * 60 * 1000).toISOString(),
    completedAt: new Date(today.getTime() - 34 * 60 * 1000).toISOString(),
    durationMs: 8400,
    tokensIn: 4520,
    tokensOut: 612,
    costoEur: 0.084,
    output: "Documentazione completa: fattura commerciale ✓, packing list ✓, B/L ✓, packing declaration ✓. Valori coerenti. Pronta per bolla doganale.",
    validationByMaster: "ok",
  },
  {
    id: "ar003",
    agentName: "CustomsFilerAgent",
    agentLabel: "Customs Filer",
    praticaId: "p002",
    praticaNumero: "PF-2026-0147",
    stato: "needs_review",
    startedAt: new Date(today.getTime() - 90 * 60 * 1000).toISOString(),
    completedAt: new Date(today.getTime() - 88 * 60 * 1000).toISOString(),
    durationMs: 12800,
    tokensIn: 6840,
    tokensOut: 1850,
    costoEur: 0.247,
    output: "Bolla precompilata. Codice HS suggerito: 9403.60 (mobili in legno). Dazio applicato: 5%. Verificare codice origine sul certificato.",
    validationByMaster: "review_needed",
  },
  {
    id: "ar004",
    agentName: "TerminalAgent",
    agentLabel: "Terminal Manager",
    praticaId: "p003",
    praticaNumero: "PF-2026-0146",
    stato: "completed",
    startedAt: new Date(today.getTime() - 180 * 60 * 1000).toISOString(),
    completedAt: new Date(today.getTime() - 178 * 60 * 1000).toISOString(),
    durationMs: 6200,
    tokensIn: 1240,
    tokensOut: 420,
    costoEur: 0.034,
    output: "ALERT: 3 container in sosta da 8 giorni @ CT Napoli (110€/g). Costo cumulato: 2640€. Suggerisco trasferimento a Conateco (75€/g). Risparmio stimato: 35€/g per container.",
    validationByMaster: "ok",
  },
  {
    id: "ar005",
    agentName: "EmailReaderAgent",
    agentLabel: "Email Reader",
    praticaId: "p008",
    praticaNumero: "PF-2026-0150",
    stato: "running",
    startedAt: new Date(today.getTime() - 30 * 1000).toISOString(),
    tokensIn: 0,
    tokensOut: 0,
  },
];

// ─── KPI ──────────────────────────────────────────────────────────────────────
export const KPI_MOCK: KpiData = {
  pratiche_aperte: 23,
  pratiche_chiuse_mese: 47,
  container_in_transito: 12,
  container_in_terminal: 5,
  fatturato_mese_eur: 184350,
  fatturato_mese_delta_pct: 12.4,
  margine_medio_pct: 18.6,
  eta_in_ritardo: 2,
  ai_runs_oggi: 38,
  ai_costo_oggi_eur: 4.82,
};

// ─── Serie storiche per grafici dashboard ────────────────────────────────────
export const FATTURATO_12M = [
  { mese: "Giu 25", fatturato: 142000, marginalita: 17.2 },
  { mese: "Lug 25", fatturato: 168000, marginalita: 18.4 },
  { mese: "Ago 25", fatturato: 124000, marginalita: 16.8 },
  { mese: "Set 25", fatturato: 198000, marginalita: 19.1 },
  { mese: "Ott 25", fatturato: 215000, marginalita: 20.2 },
  { mese: "Nov 25", fatturato: 187000, marginalita: 18.9 },
  { mese: "Dic 25", fatturato: 234000, marginalita: 21.4 },
  { mese: "Gen 26", fatturato: 156000, marginalita: 17.5 },
  { mese: "Feb 26", fatturato: 178000, marginalita: 18.2 },
  { mese: "Mar 26", fatturato: 195000, marginalita: 19.0 },
  { mese: "Apr 26", fatturato: 164000, marginalita: 17.8 },
  { mese: "Mag 26", fatturato: 184350, marginalita: 18.6 },
];

export const PRATICHE_PER_STATO = [
  { stato: "Booking aperto", count: 4 },
  { stato: "In navigazione", count: 6 },
  { stato: "In arrivo", count: 3 },
  { stato: "In dogana", count: 5 },
  { stato: "In terminal", count: 5 },
  { stato: "In consegna", count: 2 },
];

export const CARICO_PER_REPARTO = [
  { reparto: "Import", attive: 12, chiuse: 18 },
  { reparto: "Dogana", attive: 8, chiuse: 14 },
  { reparto: "Terminal", attive: 5, chiuse: 9 },
  { reparto: "Trasporti", attive: 6, chiuse: 11 },
  { reparto: "Contabilità", attive: 4, chiuse: 22 },
];

// ─── Navi attive con posizioni AIS mock ──────────────────────────────────────
export const NAVI_AIS = [
  {
    mmsi: NAVI[0].mmsi,
    nome: NAVI[0].nome,
    compagnia: NAVI[0].compagnia,
    lat: 36.5,
    lng: 14.8,
    eta: "28/05/2026",
    destinazione: "NAPLES",
    praticaNumero: "PF-2026-0148",
    cliente: CLIENTI[0].nome,
    status: "Under way — In avvicinamento",
    speedKn: 18.4,
  },
  {
    mmsi: NAVI[6].mmsi,
    nome: NAVI[6].nome,
    compagnia: NAVI[6].compagnia,
    lat: 12.5,
    lng: 45.2,
    eta: "09/06/2026",
    destinazione: "NAPLES",
    praticaNumero: "PF-2026-0149",
    cliente: CLIENTI[6].nome,
    status: "Under way — Mar Rosso",
    speedKn: 17.8,
  },
  {
    mmsi: NAVI[7].mmsi,
    nome: NAVI[7].nome,
    compagnia: NAVI[7].compagnia,
    lat: 1.3,
    lng: 103.8,
    eta: "16/06/2026",
    destinazione: "NAPLES",
    praticaNumero: "PF-2026-0150",
    cliente: CLIENTI[7].nome,
    status: "Under way — Stretto di Singapore",
    speedKn: 19.2,
  },
];

export { CLIENTI };
